// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxxghhyoetguulyokkag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4eGdoaHlvZXRndXVseW9ra2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTMwNTYsImV4cCI6MjA1NzgyOTA1Nn0.zUmfyYAQUbfuZhULSipJUk-GLdqZwtk_xZ9QunlNVWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);